// Generated by CoffeeScript 1.3.3

/*
  div class:'navbar navbar-fixed-top', ->
    div class:'navbar-inner', ->
      div class: 'container-fluid', ->
        a class:'brand', href:'#', ->
          img src:'http://l3-1.kiva.org/rgitc4f74bc5741fa37924bcec931446088f7bfdaee1/img/logo/kiva.png'
        input type:'text', class:'search span2', placeholder:'search loans'
        span class:'pledges-header', ->
          div ->
            h2 'Your pledges total: $'
            h2 class:'pledge-total', '0'
          span class:'label label-success pledge-link', '&uarr; go there'
        div class:'messageArea'
*/


/*
@collection.on 'resorted', (m)=>
  # remove this table row from the list view 
  # and reinsert it at it's new sorted index
  # according to the collection
  # this type of sort is more efficient 
  # than re-rendering the entire list view
  
  if m.pledge is 0 and not m.lastChangeIsPositive
    m.view.$el.remove()
  modelIds = _.pluck @collection.models, 'id'
  newIndex = _.indexOf modelIds, m.get('id')
  m.view.$el.slideUp 1000, =>
    m.view.$el.remove()
    m.view.$el.insertBefore($(@$('tbody.my-loans tr')[newIndex])).slideDown(500)
    m.view.delegateEvents()
  @delegateEvents()
*/


(function() {



}).call(this);
